-- MySQL Script generated by MySQL Workbench
-- Fri May 29 04:24:29 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema invilara
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema invilara
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `invilara` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `invilara` ;

-- -----------------------------------------------------
-- Table `invilara`.`solicitante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invilara`.`solicitante` ;

CREATE TABLE IF NOT EXISTS `invilara`.`solicitante` (
  `id_solicitante` INT NOT NULL AUTO_INCREMENT,
  `nombre_solicitante` VARCHAR(90) NOT NULL,
  `parroquia` VARCHAR(45) NOT NULL,
  `municipio` VARCHAR(45) NOT NULL,
  `ambito` VARCHAR(45) NOT NULL,
  `rif` VARCHAR(45) NOT NULL,
  `cedula` VARCHAR(10) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_solicitante`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre_solicitante` ASC) VISIBLE,
  UNIQUE INDEX `rif_UNIQUE` (`rif` ASC) VISIBLE,
  UNIQUE INDEX `cedula_UNIQUE` (`cedula` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla de los solicitantes';


-- -----------------------------------------------------
-- Table `invilara`.`informe_avance_obra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invilara`.`informe_avance_obra` ;

CREATE TABLE IF NOT EXISTS `invilara`.`informe_avance_obra` (
  `id_informe` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `tipo_obras` VARCHAR(25) NOT NULL,
  `estado` VARCHAR(25) NOT NULL,
  `recurso` INT NOT NULL,
  `poblacion_benefiada` VARCHAR(45) NOT NULL,
  `logros` VARCHAR(45) NOT NULL,
  `tipo_informe` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_informe`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla de informes de avances de obras';


-- -----------------------------------------------------
-- Table `invilara`.`gerencias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invilara`.`gerencias` ;

CREATE TABLE IF NOT EXISTS `invilara`.`gerencias` (
  `id_gerencias` INT NOT NULL AUTO_INCREMENT,
  `nombre_gerencia` VARCHAR(45) NOT NULL,
  `direccion_gerencia` VARCHAR(45) NOT NULL,
  `informe_avance_obra_id_informe` INT NOT NULL,
  PRIMARY KEY (`id_gerencias`, `informe_avance_obra_id_informe`),
  UNIQUE INDEX `nombre_gerencia_UNIQUE` (`nombre_gerencia` ASC) VISIBLE,
  INDEX `fk_gerencias_informe_avance_obra1_idx` (`informe_avance_obra_id_informe` ASC) VISIBLE,
  CONSTRAINT `fk_gerencias_informe_avance_obra1`
    FOREIGN KEY (`informe_avance_obra_id_informe`)
    REFERENCES `invilara`.`informe_avance_obra` (`id_informe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla de las gerencias';


-- -----------------------------------------------------
-- Table `invilara`.`maquinaria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invilara`.`maquinaria` ;

CREATE TABLE IF NOT EXISTS `invilara`.`maquinaria` (
  `id_maquinaria` INT NOT NULL AUTO_INCREMENT,
  `nombre_maquinaria` VARCHAR(50) NOT NULL COMMENT 'Tabla de nombres de maquinarias',
  PRIMARY KEY (`id_maquinaria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invilara`.`gestionar_proyectos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invilara`.`gestionar_proyectos` ;

CREATE TABLE IF NOT EXISTS `invilara`.`gestionar_proyectos` (
  `id_proyectos` INT NOT NULL AUTO_INCREMENT,
  `codigo_proyecto` VARCHAR(15) NOT NULL,
  `fecha_planificacion` DATETIME NOT NULL,
  `descripcion_tecnica` VARCHAR(200) NOT NULL,
  `computos_metricos` VARCHAR(255) NOT NULL,
  `estimacion_costo_proyecto` VARCHAR(45) NOT NULL,
  `inspecciones_previas` VARCHAR(255) NOT NULL,
  `maquinaria_id_maquinaria` INT NOT NULL,
  `gerencias_id_gerencias` INT NOT NULL,
  PRIMARY KEY (`id_proyectos`, `maquinaria_id_maquinaria`, `gerencias_id_gerencias`),
  UNIQUE INDEX `codigo_proyecto_UNIQUE` (`codigo_proyecto` ASC) VISIBLE,
  INDEX `fk_gestionar_proyectos_maquinaria_idx` (`maquinaria_id_maquinaria` ASC) VISIBLE,
  INDEX `fk_gestionar_proyectos_gerencias1_idx` (`gerencias_id_gerencias` ASC) VISIBLE,
  CONSTRAINT `fk_gestionar_proyectos_maquinaria`
    FOREIGN KEY (`maquinaria_id_maquinaria`)
    REFERENCES `invilara`.`maquinaria` (`id_maquinaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gestionar_proyectos_gerencias1`
    FOREIGN KEY (`gerencias_id_gerencias`)
    REFERENCES `invilara`.`gerencias` (`id_gerencias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla de gestion de proyectos';


-- -----------------------------------------------------
-- Table `invilara`.`inspectores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invilara`.`inspectores` ;

CREATE TABLE IF NOT EXISTS `invilara`.`inspectores` (
  `id_inspector` INT NOT NULL AUTO_INCREMENT,
  `nombre_inspector` VARCHAR(45) NOT NULL,
  `cedula` VARCHAR(10) NOT NULL,
  `telefono_inspector` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`id_inspector`),
  UNIQUE INDEX `cedula_UNIQUE` (`cedula` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invilara`.`gestionar_obra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invilara`.`gestionar_obra` ;

CREATE TABLE IF NOT EXISTS `invilara`.`gestionar_obra` (
  `id_inspeccion` INT NOT NULL AUTO_INCREMENT,
  `nombre_ing_insp` VARCHAR(45) NOT NULL,
  `periodo_ejecucion` INT NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `mediciones_obra` VARCHAR(45) NOT NULL,
  `valuaciones` VARCHAR(100) NOT NULL,
  `modificaciones_contrato` VARCHAR(100) NOT NULL,
  `certificaciones_obras_ejecutadas` INT NOT NULL,
  `numero_contrato` VARCHAR(20) NOT NULL,
  `porcentaje_avance_obra` INT NOT NULL,
  `inspectores_id_inspector` INT NOT NULL,
  PRIMARY KEY (`id_inspeccion`, `inspectores_id_inspector`),
  INDEX `fk_gestionar_obra_inspectores1_idx` (`inspectores_id_inspector` ASC) VISIBLE,
  CONSTRAINT `fk_gestionar_obra_inspectores1`
    FOREIGN KEY (`inspectores_id_inspector`)
    REFERENCES `invilara`.`inspectores` (`id_inspector`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla de las inspecciones';


-- -----------------------------------------------------
-- Table `invilara`.`empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invilara`.`empresa` ;

CREATE TABLE IF NOT EXISTS `invilara`.`empresa` (
  `rif` VARCHAR(12) NOT NULL,
  `nombre_empresa` VARCHAR(80) NOT NULL,
  `telefono` VARCHAR(12) NOT NULL COMMENT 'Tabla de empresas.',
  `domicilio_fiscal` VARCHAR(100) NOT NULL,
  `gestionar_proyectos_id_proyectos` INT NOT NULL,
  `gestionar_proyectos_maquinaria_id_maquinaria` INT NOT NULL,
  `gestionar_obra_id_inspeccion` INT NOT NULL,
  PRIMARY KEY (`rif`, `gestionar_proyectos_id_proyectos`, `gestionar_proyectos_maquinaria_id_maquinaria`, `gestionar_obra_id_inspeccion`),
  UNIQUE INDEX `rif_UNIQUE` (`rif` ASC) VISIBLE,
  INDEX `fk_empresa_gestionar_proyectos1_idx` (`gestionar_proyectos_id_proyectos` ASC, `gestionar_proyectos_maquinaria_id_maquinaria` ASC) VISIBLE,
  INDEX `fk_empresa_gestionar_obra1_idx` (`gestionar_obra_id_inspeccion` ASC) VISIBLE,
  CONSTRAINT `fk_empresa_gestionar_proyectos1`
    FOREIGN KEY (`gestionar_proyectos_id_proyectos` , `gestionar_proyectos_maquinaria_id_maquinaria`)
    REFERENCES `invilara`.`gestionar_proyectos` (`id_proyectos` , `maquinaria_id_maquinaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empresa_gestionar_obra1`
    FOREIGN KEY (`gestionar_obra_id_inspeccion`)
    REFERENCES `invilara`.`gestionar_obra` (`id_inspeccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invilara`.`gestionar_contrataciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invilara`.`gestionar_contrataciones` ;

CREATE TABLE IF NOT EXISTS `invilara`.`gestionar_contrataciones` (
  `id_contratacion` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NOT NULL,
  `empresa_ganadora` VARCHAR(30) NOT NULL,
  `numero_contrato` VARCHAR(12) NOT NULL,
  `monto` VARCHAR(20) NOT NULL,
  `fecha_inicio_procedimiento` DATETIME NOT NULL,
  `fecha_adjudicacion` DATETIME NOT NULL,
  `tipo_contrato` VARCHAR(30) NOT NULL,
  `modalidad` VARCHAR(30) NOT NULL,
  `objeto` VARCHAR(30) NOT NULL,
  `observacion` VARCHAR(100) NOT NULL,
  `fecha_registro` DATETIME NOT NULL,
  `gestionar_proyectos_id_proyectos` INT NOT NULL,
  `gestionar_proyectos_maquinaria_id_maquinaria` INT NOT NULL,
  `empresa_rif` VARCHAR(12) NOT NULL,
  `empresa_gestionar_proyectos_id_proyectos` INT NOT NULL,
  `empresa_gestionar_proyectos_maquinaria_id_maquinaria` INT NOT NULL,
  PRIMARY KEY (`id_contratacion`, `gestionar_proyectos_id_proyectos`, `gestionar_proyectos_maquinaria_id_maquinaria`, `empresa_rif`, `empresa_gestionar_proyectos_id_proyectos`, `empresa_gestionar_proyectos_maquinaria_id_maquinaria`),
  UNIQUE INDEX `numero_contrato_UNIQUE` (`numero_contrato` ASC) VISIBLE,
  INDEX `fk_gestionar_contrataciones_gestionar_proyectos1_idx` (`gestionar_proyectos_id_proyectos` ASC, `gestionar_proyectos_maquinaria_id_maquinaria` ASC) VISIBLE,
  INDEX `fk_gestionar_contrataciones_empresa1_idx` (`empresa_rif` ASC, `empresa_gestionar_proyectos_id_proyectos` ASC, `empresa_gestionar_proyectos_maquinaria_id_maquinaria` ASC) VISIBLE,
  CONSTRAINT `fk_gestionar_contrataciones_gestionar_proyectos1`
    FOREIGN KEY (`gestionar_proyectos_id_proyectos` , `gestionar_proyectos_maquinaria_id_maquinaria`)
    REFERENCES `invilara`.`gestionar_proyectos` (`id_proyectos` , `maquinaria_id_maquinaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gestionar_contrataciones_empresa1`
    FOREIGN KEY (`empresa_rif` , `empresa_gestionar_proyectos_id_proyectos` , `empresa_gestionar_proyectos_maquinaria_id_maquinaria`)
    REFERENCES `invilara`.`empresa` (`rif` , `gestionar_proyectos_id_proyectos` , `gestionar_proyectos_maquinaria_id_maquinaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Tabla de contrataciones';


-- -----------------------------------------------------
-- Table `invilara`.`gestionar_solicitudes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invilara`.`gestionar_solicitudes` ;

CREATE TABLE IF NOT EXISTS `invilara`.`gestionar_solicitudes` (
  `id_solicitud` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `telefono_solicitante` VARCHAR(12) NOT NULL,
  `direccion_solicitante` VARCHAR(100) NOT NULL,
  `tipo_solicitud` VARCHAR(45) NOT NULL,
  `estatus_solicitud` VARCHAR(15) NOT NULL,
  `problematica` VARCHAR(255) NOT NULL,
  `tipo_solicitante` VARCHAR(45) NOT NULL,
  `solicitante_id_comunidad` INT NOT NULL,
  PRIMARY KEY (`id_solicitud`, `solicitante_id_comunidad`),
  INDEX `fk_gestionar_solicitudes_solicitante1_idx` (`solicitante_id_comunidad` ASC) VISIBLE,
  CONSTRAINT `fk_gestionar_solicitudes_solicitante1`
    FOREIGN KEY (`solicitante_id_comunidad`)
    REFERENCES `invilara`.`solicitante` (`id_comunidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla general de las solicitudes';


-- -----------------------------------------------------
-- Table `invilara`.`reporte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invilara`.`reporte` ;

CREATE TABLE IF NOT EXISTS `invilara`.`reporte` (
  `id_reporte` INT NOT NULL AUTO_INCREMENT,
  `titulo_obra` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `ubicacion_obra` VARCHAR(80) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `tipo_obra` VARCHAR(30) NOT NULL,
  `fecha` DATETIME NOT NULL,
  `municipio` VARCHAR(30) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `parroquia` VARCHAR(30) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `solicitudes_pendientes` INT NOT NULL,
  `solicitudes_procesadas` INT NOT NULL,
  `cantidad_total_solicitudes` INT NOT NULL,
  `cantidad_comunidades_atendidas` INT NOT NULL,
  `institucion` VARCHAR(45) NOT NULL,
  `gerencia` VARCHAR(45) NOT NULL,
  `evidencia_antes` VARCHAR(50) NOT NULL,
  `evidencia_durante` VARCHAR(50) NOT NULL,
  `evidencia_despues` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_reporte`),
  UNIQUE INDEX `titulo_obra_UNIQUE` (`titulo_obra` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `invilara`.`empleados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invilara`.`empleados` ;

CREATE TABLE IF NOT EXISTS `invilara`.`empleados` (
  `id_empleados` INT NOT NULL AUTO_INCREMENT,
  `nombre_gerente` VARCHAR(45) NOT NULL,
  `cedula_gerente` VARCHAR(10) NOT NULL,
  `telefono_gerente` VARCHAR(12) NOT NULL,
  `direccion_gerente` VARCHAR(100) NOT NULL,
  `correo_gerente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_empleados`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invilara`.`gestionar_prioridad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invilara`.`gestionar_prioridad` ;

CREATE TABLE IF NOT EXISTS `invilara`.`gestionar_prioridad` (
  `id_gestion_prioridad` INT NOT NULL AUTO_INCREMENT,
  `rango_prioridad` FLOAT NOT NULL,
  `fecha_asignacion` DATETIME NOT NULL,
  `responsable_ajuste` VARCHAR(30) NOT NULL,
  `justificacion_cambio` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id_gestion_prioridad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invilara`.`gestionar_gravedad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invilara`.`gestionar_gravedad` ;

CREATE TABLE IF NOT EXISTS `invilara`.`gestionar_gravedad` (
  `id_gravedad` INT NOT NULL AUTO_INCREMENT,
  `nivel_gravedad` VARCHAR(20) NOT NULL,
  `criticidad` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_gravedad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invilara`.`priorizar_solicitudes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invilara`.`priorizar_solicitudes` ;

CREATE TABLE IF NOT EXISTS `invilara`.`priorizar_solicitudes` (
  `id_priorizacion` INT NOT NULL AUTO_INCREMENT,
  `analisis_narrativo_ia` VARCHAR(255) NOT NULL,
  `prioridad_calculada` FLOAT NOT NULL,
  `estatus` VARCHAR(15) NOT NULL,
  `fecha_procesamiento` DATETIME NOT NULL,
  `gestionar_prioridad_id_gestion_prioridad` INT NOT NULL,
  `gestionar_gravedad_id_gravedad` INT NOT NULL,
  `gestionar_solicitudes_id_solicitud` INT NOT NULL,
  PRIMARY KEY (`id_priorizacion`, `gestionar_prioridad_id_gestion_prioridad`, `gestionar_gravedad_id_gravedad`, `gestionar_solicitudes_id_solicitud`),
  INDEX `fk_priorizar_solicitudes_gestionar_prioridad1_idx` (`gestionar_prioridad_id_gestion_prioridad` ASC) VISIBLE,
  INDEX `fk_priorizar_solicitudes_gestionar_gravedad1_idx` (`gestionar_gravedad_id_gravedad` ASC) VISIBLE,
  INDEX `fk_priorizar_solicitudes_gestionar_solicitudes1_idx` (`gestionar_solicitudes_id_solicitud` ASC) VISIBLE,
  CONSTRAINT `fk_priorizar_solicitudes_gestionar_prioridad1`
    FOREIGN KEY (`gestionar_prioridad_id_gestion_prioridad`)
    REFERENCES `invilara`.`gestionar_prioridad` (`id_gestion_prioridad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_priorizar_solicitudes_gestionar_gravedad1`
    FOREIGN KEY (`gestionar_gravedad_id_gravedad`)
    REFERENCES `invilara`.`gestionar_gravedad` (`id_gravedad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_priorizar_solicitudes_gestionar_solicitudes1`
    FOREIGN KEY (`gestionar_solicitudes_id_solicitud`)
    REFERENCES `invilara`.`gestionar_solicitudes` (`id_solicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invilara`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invilara`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `invilara`.`usuarios` (
  `id_usuarios` INT NOT NULL AUTO_INCREMENT,
  `cedula_usuario` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(8) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `rol` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_usuarios`),
  UNIQUE INDEX `cedula_usuario_UNIQUE` (`cedula_usuario` ASC) VISIBLE,
  UNIQUE INDEX `contraseña_UNIQUE` (`contraseña` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invilara`.`gerencias_has_empleados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invilara`.`gerencias_has_empleados` ;

CREATE TABLE IF NOT EXISTS `invilara`.`gerencias_has_empleados` (
  `gerencias_id_gerencias` INT NOT NULL,
  `empleados_id_empleados` INT NOT NULL,
  PRIMARY KEY (`gerencias_id_gerencias`, `empleados_id_empleados`),
  INDEX `fk_gerencias_has_empleados_empleados1_idx` (`empleados_id_empleados` ASC) VISIBLE,
  INDEX `fk_gerencias_has_empleados_gerencias1_idx` (`gerencias_id_gerencias` ASC) VISIBLE,
  CONSTRAINT `fk_gerencias_has_empleados_gerencias1`
    FOREIGN KEY (`gerencias_id_gerencias`)
    REFERENCES `invilara`.`gerencias` (`id_gerencias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gerencias_has_empleados_empleados1`
    FOREIGN KEY (`empleados_id_empleados`)
    REFERENCES `invilara`.`empleados` (`id_empleados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `invilara`.`gestionar_publicaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invilara`.`gestionar_publicaciones` ;

CREATE TABLE IF NOT EXISTS `invilara`.`gestionar_publicaciones` (
  `id_publicaciones` INT NOT NULL AUTO_INCREMENT,
  `titulo_publicacion` VARCHAR(150) NOT NULL,
  `nombre_responsable` VARCHAR(45) NOT NULL,
  `tipo_publicacion` VARCHAR(15) NOT NULL,
  `fecha_publicacion` DATETIME NOT NULL COMMENT 'Tabla de gestion de publicaciones',
  PRIMARY KEY (`id_publicaciones`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invilara`.`informe_avance_obra_has_gestionar_publicaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invilara`.`informe_avance_obra_has_gestionar_publicaciones` ;

CREATE TABLE IF NOT EXISTS `invilara`.`informe_avance_obra_has_gestionar_publicaciones` (
  `informe_avance_obra_id_informe` INT NOT NULL,
  `gestionar_publicaciones_id_publicaciones` INT NOT NULL,
  PRIMARY KEY (`informe_avance_obra_id_informe`, `gestionar_publicaciones_id_publicaciones`),
  INDEX `fk_informe_avance_obra_has_gestionar_publicaciones_gestiona_idx` (`gestionar_publicaciones_id_publicaciones` ASC) VISIBLE,
  INDEX `fk_informe_avance_obra_has_gestionar_publicaciones_informe__idx` (`informe_avance_obra_id_informe` ASC) VISIBLE,
  CONSTRAINT `fk_informe_avance_obra_has_gestionar_publicaciones_informe_av1`
    FOREIGN KEY (`informe_avance_obra_id_informe`)
    REFERENCES `invilara`.`informe_avance_obra` (`id_informe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_informe_avance_obra_has_gestionar_publicaciones_gestionar_1`
    FOREIGN KEY (`gestionar_publicaciones_id_publicaciones`)
    REFERENCES `invilara`.`gestionar_publicaciones` (`id_publicaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `invilara`.`gerencias_has_gestionar_prioridad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invilara`.`gerencias_has_gestionar_prioridad` ;

CREATE TABLE IF NOT EXISTS `invilara`.`gerencias_has_gestionar_prioridad` (
  `gerencias_id_gerencias` INT NOT NULL,
  `gerencias_informe_avance_obra_id_informe` INT NOT NULL,
  `gestionar_prioridad_id_gestion_prioridad` INT NOT NULL,
  PRIMARY KEY (`gerencias_id_gerencias`, `gerencias_informe_avance_obra_id_informe`, `gestionar_prioridad_id_gestion_prioridad`),
  INDEX `fk_gerencias_has_gestionar_prioridad_gestionar_prioridad1_idx` (`gestionar_prioridad_id_gestion_prioridad` ASC) VISIBLE,
  INDEX `fk_gerencias_has_gestionar_prioridad_gerencias1_idx` (`gerencias_id_gerencias` ASC, `gerencias_informe_avance_obra_id_informe` ASC) VISIBLE,
  CONSTRAINT `fk_gerencias_has_gestionar_prioridad_gerencias1`
    FOREIGN KEY (`gerencias_id_gerencias` , `gerencias_informe_avance_obra_id_informe`)
    REFERENCES `invilara`.`gerencias` (`id_gerencias` , `informe_avance_obra_id_informe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gerencias_has_gestionar_prioridad_gestionar_prioridad1`
    FOREIGN KEY (`gestionar_prioridad_id_gestion_prioridad`)
    REFERENCES `invilara`.`gestionar_prioridad` (`id_gestion_prioridad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
