-- MySQL Script generated by MySQL Workbench
-- Sun Jun 14 19:23:26 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema invilara
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `empresa`
-- -----------------------------------------------------

CREATE DATABASE IF NOT EXISTS invilara;
USE invilara;

DROP TABLE IF EXISTS `empresa` ;

CREATE TABLE IF NOT EXISTS `empresa` (
  `rif` VARCHAR(12) NOT NULL,
  `nombre_empresa` VARCHAR(80) NOT NULL,
  `telefono` VARCHAR(12) NOT NULL COMMENT 'Tabla de empresas.',
  `domicilio_fiscal` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`rif`),
  UNIQUE INDEX `rif_UNIQUE` (`rif` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contratacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `contratacion` ;

CREATE TABLE IF NOT EXISTS `contratacion` (
  `id_contratacion` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NOT NULL,
  `empresa_ganadora` VARCHAR(30) NOT NULL,
  `numero_contrato` VARCHAR(12) NOT NULL,
  `monto` VARCHAR(20) NOT NULL,
  `fecha_inicio_procedimiento` DATETIME NOT NULL,
  `fecha_adjudicacion` DATETIME NOT NULL,
  `tipo_contrato` VARCHAR(30) NOT NULL,
  `modalidad` VARCHAR(30) NOT NULL,
  `objeto` VARCHAR(30) NOT NULL,
  `observacion` VARCHAR(100) NOT NULL,
  `fecha_registro` DATETIME NOT NULL,
  `empresa_rif` VARCHAR(12) NOT NULL,
  UNIQUE INDEX `numero_contrato_UNIQUE` (`numero_contrato` ASC),
  PRIMARY KEY (`id_contratacion`),
  INDEX `fk_contratacion_empresa1_idx` (`empresa_rif` ASC),
  CONSTRAINT `fk_contratacion_empresa1`
    FOREIGN KEY (`empresa_rif`)
    REFERENCES `empresa` (`rif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Tabla de contrataciones';


-- -----------------------------------------------------
-- Table `semaforo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `semaforo` ;

CREATE TABLE IF NOT EXISTS `semaforo` (
  `id_semaforo` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(20) NOT NULL,
  `color` ENUM('VERDE', 'AMARILLO', 'ROJO') NOT NULL,
  `descripcion` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_semaforo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto` ;

CREATE TABLE IF NOT EXISTS `proyecto` (
  `codigo_proyecto` VARCHAR(15) NOT NULL,
  `fecha_planificacion` DATETIME NOT NULL,
  `descripcion_tecnica` VARCHAR(200) NOT NULL,
  `computos_metricos` VARCHAR(255) NOT NULL,
  `estimacion_costo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo_proyecto`),
  UNIQUE INDEX `codigo_proyecto_UNIQUE` (`codigo_proyecto` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci
COMMENT = 'Tabla de gestion de proyectos';


-- -----------------------------------------------------
-- Table `obra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `obra` ;

CREATE TABLE IF NOT EXISTS `obra` (
  `id_obra` INT NOT NULL AUTO_INCREMENT,
  `titulo_obra` VARCHAR(45) NOT NULL,
  `ubicacion_obra` VARCHAR(80) NOT NULL,
  `periodo_ejecucion` INT NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `mediciones_obra` VARCHAR(45) NOT NULL,
  `valuaciones` VARCHAR(100) NOT NULL,
  `modificaciones_contrato` VARCHAR(100) NOT NULL,
  `certificaciones_obras_ejecutadas` INT NOT NULL,
  `numero_contrato` VARCHAR(20) NOT NULL,
  `porcentaje_avance_obra` INT NOT NULL,
  `semaforo_id_semaforo` INT NOT NULL,
  `contratacion_id_contratacion` INT NOT NULL,
  `gestionar_proyectos_codigo_proyecto` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_obra`, `semaforo_id_semaforo`, `contratacion_id_contratacion`, `gestionar_proyectos_codigo_proyecto`),
  INDEX `fk_obra_semaforo1_idx` (`semaforo_id_semaforo` ASC),
  INDEX `fk_obra_contratacion1_idx` (`contratacion_id_contratacion` ASC),
  INDEX `fk_obra_gestionar_proyectos1_idx` (`gestionar_proyectos_codigo_proyecto` ASC),
  UNIQUE INDEX `id_obra_UNIQUE` (`id_obra` ASC),
  CONSTRAINT `fk_obra_semaforo1`
    FOREIGN KEY (`semaforo_id_semaforo`)
    REFERENCES `semaforo` (`id_semaforo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_obra_contratacion1`
    FOREIGN KEY (`contratacion_id_contratacion`)
    REFERENCES `contratacion` (`id_contratacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_obra_gestionar_proyectos1`
    FOREIGN KEY (`gestionar_proyectos_codigo_proyecto`)
    REFERENCES `proyecto` (`codigo_proyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci
COMMENT = 'Tabla de las inspecciones';


-- -----------------------------------------------------
-- Table `persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `persona` ;

CREATE TABLE IF NOT EXISTS `persona` (
  `id_persona` INT NOT NULL AUTO_INCREMENT,
  `cedula_persona` INT NOT NULL,
  `direccion` VARCHAR(200) NOT NULL,
  `parroquia` VARCHAR(45) NOT NULL,
  `municipio` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(12) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `cedula_persona_UNIQUE` (`cedula_persona` ASC),
  PRIMARY KEY (`id_persona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prioridad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prioridad` ;

CREATE TABLE IF NOT EXISTS `prioridad` (
  `id_gestion_prioridad` INT NOT NULL AUTO_INCREMENT,
  `rango_prioridad` FLOAT NOT NULL,
  `fecha_asignacion` DATETIME NOT NULL,
  `responsable_ajuste` VARCHAR(30) NOT NULL,
  `justificacion_cambio` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id_gestion_prioridad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `solicitudes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `solicitudes` ;

CREATE TABLE IF NOT EXISTS `solicitudes` (
  `id_solicitudes` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `tipo_solicitud` VARCHAR(45) NOT NULL,
  `estatus_solicitud` VARCHAR(15) NOT NULL,
  `problematica` VARCHAR(255) NOT NULL,
  `persona_id_persona` INT NOT NULL,
  `prioridad_id_gestion_prioridad` INT NOT NULL,
  PRIMARY KEY (`id_solicitudes`, `persona_id_persona`, `prioridad_id_gestion_prioridad`),
  INDEX `fk_solicitudes_persona1_idx` (`persona_id_persona` ASC),
  INDEX `fk_solicitudes_prioridad1_idx` (`prioridad_id_gestion_prioridad` ASC),
  CONSTRAINT `fk_solicitudes_persona1`
    FOREIGN KEY (`persona_id_persona`)
    REFERENCES `persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitudes_prioridad1`
    FOREIGN KEY (`prioridad_id_gestion_prioridad`)
    REFERENCES `prioridad` (`id_gestion_prioridad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci
COMMENT = 'Tabla general de las solicitudes';


-- -----------------------------------------------------
-- Table `avance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avance` ;

CREATE TABLE IF NOT EXISTS `avance` (
  `id_avance` VARCHAR(45) NOT NULL,
  `porcentaje_avance` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `gerente` VARCHAR(45) NOT NULL,
  `fecha_avance` DATE NOT NULL,
  `obra_id_obra` INT NOT NULL,
  `obra_semaforo_id_semaforo` INT NOT NULL,
  `obra_contratacion_id_contratacion` INT NOT NULL,
  `obra_gestionar_proyectos_codigo_proyecto` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_avance`),
  INDEX `fk_avance_obra1_idx` (`obra_id_obra` ASC, `obra_semaforo_id_semaforo` ASC, `obra_contratacion_id_contratacion` ASC, `obra_gestionar_proyectos_codigo_proyecto` ASC),
  CONSTRAINT `fk_avance_obra1`
    FOREIGN KEY (`obra_id_obra` , `obra_semaforo_id_semaforo` , `obra_contratacion_id_contratacion` , `obra_gestionar_proyectos_codigo_proyecto`)
    REFERENCES `obra` (`id_obra` , `semaforo_id_semaforo` , `contratacion_id_contratacion` , `gestionar_proyectos_codigo_proyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `informe_avance_obra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `informe_avance_obra` ;

CREATE TABLE IF NOT EXISTS `informe_avance_obra` (
  `id_informe` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `estado` VARCHAR(25) NOT NULL,
  `poblacion_benefiada` VARCHAR(45) NOT NULL,
  `tipo_informe` VARCHAR(30) NOT NULL,
  `evidencia_antes` VARCHAR(50) NOT NULL,
  `evidencia_durante` VARCHAR(50) NOT NULL,
  `evidencia_despues` VARCHAR(50) NOT NULL,
  `avance_id_avance` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_informe`),
  INDEX `fk_informe_avance_obra_avance1_idx` (`avance_id_avance` ASC),
  CONSTRAINT `fk_informe_avance_obra_avance1`
    FOREIGN KEY (`avance_id_avance`)
    REFERENCES `avance` (`id_avance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci
COMMENT = 'Tabla de informes de avances de obras';


-- -----------------------------------------------------
-- Table `reporte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reporte` ;

CREATE TABLE IF NOT EXISTS `reporte` (
  `id_reporte` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `ubicacion` VARCHAR(255) NOT NULL,
  `solicitudes_pendientes` INT NOT NULL,
  `solicitudes_procesadas` INT NOT NULL,
  `cantidad_total_solicitudes` INT NOT NULL,
  `cantidad_comunidades_atendidas` INT NOT NULL,
  `informe_avance_obra_id_informe` INT NOT NULL,
  PRIMARY KEY (`id_reporte`),
  INDEX `fk_reporte_informe_avance_obra1_idx` (`informe_avance_obra_id_informe` ASC),
  CONSTRAINT `fk_reporte_informe_avance_obra1`
    FOREIGN KEY (`informe_avance_obra_id_informe`)
    REFERENCES `informe_avance_obra` (`id_informe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `maquinaria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maquinaria` ;

CREATE TABLE IF NOT EXISTS `maquinaria` (
  `id_maquinaria` INT NOT NULL AUTO_INCREMENT,
  `nombre_maquinaria` VARCHAR(50) NOT NULL COMMENT 'Tabla de nombres de maquinarias',
  `tipo_maquinaria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_maquinaria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evidencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `evidencia` ;

CREATE TABLE IF NOT EXISTS `evidencia` (
  `id_evidencia` INT NOT NULL AUTO_INCREMENT,
  `fotos` VARCHAR(45) NOT NULL,
  `url_archivos` VARCHAR(90) NOT NULL,
  `fecha_registro` DATETIME NOT NULL,
  PRIMARY KEY (`id_evidencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inspeccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inspeccion` ;

CREATE TABLE IF NOT EXISTS `inspeccion` (
  `id_inspeccion` INT NOT NULL AUTO_INCREMENT,
  `inspector` VARCHAR(45) NOT NULL,
  `fecha_inspeccion` DATE NOT NULL,
  `tipo_inspeccion` VARCHAR(45) NOT NULL,
  `observaciones` VARCHAR(255) NOT NULL,
  `obra_id_obra` INT NOT NULL,
  `obra_semaforo_id_semaforo` INT NOT NULL,
  `obra_contratacion_id_contratacion` INT NOT NULL,
  `obra_gestionar_proyectos_codigo_proyecto` VARCHAR(15) NOT NULL,
  `obra_id_obra1` INT NOT NULL,
  `obra_semaforo_id_semaforo1` INT NOT NULL,
  `obra_contratacion_id_contratacion1` INT NOT NULL,
  `obra_gestionar_proyectos_codigo_proyecto1` VARCHAR(15) NOT NULL,
  `evidencia_id_evidencia` INT NOT NULL,
  PRIMARY KEY (`id_inspeccion`, `evidencia_id_evidencia`),
  UNIQUE INDEX `cedula_UNIQUE` (`fecha_inspeccion` ASC),
  INDEX `fk_inspeccion_obra1_idx` (`obra_id_obra1` ASC, `obra_semaforo_id_semaforo1` ASC, `obra_contratacion_id_contratacion1` ASC, `obra_gestionar_proyectos_codigo_proyecto1` ASC),
  INDEX `fk_inspeccion_evidencia1_idx` (`evidencia_id_evidencia` ASC),
  CONSTRAINT `fk_inspeccion_obra1`
    FOREIGN KEY (`obra_id_obra1` , `obra_semaforo_id_semaforo1` , `obra_contratacion_id_contratacion1` , `obra_gestionar_proyectos_codigo_proyecto1`)
    REFERENCES `obra` (`id_obra` , `semaforo_id_semaforo` , `contratacion_id_contratacion` , `gestionar_proyectos_codigo_proyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inspeccion_evidencia1`
    FOREIGN KEY (`evidencia_id_evidencia`)
    REFERENCES `evidencia` (`id_evidencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empleados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `empleados` ;

CREATE TABLE IF NOT EXISTS `empleados` (
  `id_empleados` INT NOT NULL AUTO_INCREMENT,
  `nombre_empleado` VARCHAR(45) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `fecha_ingreso` DATE NOT NULL,
  `gerencia_asignada` VARCHAR(45) NOT NULL,
  `persona_id_persona` INT NOT NULL,
  PRIMARY KEY (`id_empleados`),
  INDEX `fk_empleados_persona1_idx` (`persona_id_persona` ASC),
  CONSTRAINT `fk_empleados_persona1`
    FOREIGN KEY (`persona_id_persona`)
    REFERENCES `persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gravedad_obra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gravedad_obra` ;

CREATE TABLE IF NOT EXISTS `gravedad_obra` (
  `id_gravedad` INT NOT NULL AUTO_INCREMENT,
  `nivel_gravedad` VARCHAR(20) NOT NULL,
  `criticidad` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_gravedad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `publicacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `publicacion` ;

CREATE TABLE IF NOT EXISTS `publicacion` (
  `id_publicacion` INT NOT NULL AUTO_INCREMENT,
  `titulo_publicacion` VARCHAR(150) NOT NULL,
  `nombre_responsable` VARCHAR(45) NOT NULL,
  `tipo_publicacion` VARCHAR(15) NOT NULL,
  `fecha_publicacion` DATETIME NOT NULL COMMENT 'Tabla de gestion de publicaciones',
  `informe_avance_obra_id_informe` INT NOT NULL,
  PRIMARY KEY (`id_publicacion`),
  INDEX `fk_publicacion_informe_avance_obra1_idx` (`informe_avance_obra_id_informe` ASC),
  CONSTRAINT `fk_publicacion_informe_avance_obra1`
    FOREIGN KEY (`informe_avance_obra_id_informe`)
    REFERENCES `informe_avance_obra` (`id_informe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `particular`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `particular` ;

CREATE TABLE IF NOT EXISTS `particular` (
  `id_particular` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `persona_id_persona` INT NOT NULL,
  PRIMARY KEY (`id_particular`, `persona_id_persona`),
  INDEX `fk_particular_persona1_idx` (`persona_id_persona` ASC),
  CONSTRAINT `fk_particular_persona1`
    FOREIGN KEY (`persona_id_persona`)
    REFERENCES `persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comunidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comunidad` ;

CREATE TABLE IF NOT EXISTS `comunidad` (
  `id_comunidad` INT NOT NULL AUTO_INCREMENT,
  `nombre_comunidad` VARCHAR(100) NOT NULL,
  `ambito` VARCHAR(45) NOT NULL,
  `sector` VARCHAR(45) NOT NULL,
  `persona_id_persona` INT NOT NULL,
  PRIMARY KEY (`id_comunidad`, `persona_id_persona`),
  INDEX `fk_comunidad_persona1_idx` (`persona_id_persona` ASC),
  CONSTRAINT `fk_comunidad_persona1`
    FOREIGN KEY (`persona_id_persona`)
    REFERENCES `persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `institucion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `institucion` ;

CREATE TABLE IF NOT EXISTS `institucion` (
  `id_institucion` INT NOT NULL AUTO_INCREMENT,
  `nombre_representante` VARCHAR(45) NOT NULL,
  `razon_social` VARCHAR(120) NOT NULL,
  `persona_id_persona` INT NOT NULL,
  PRIMARY KEY (`id_institucion`, `persona_id_persona`),
  INDEX `fk_institucion_persona1_idx` (`persona_id_persona` ASC),
  CONSTRAINT `fk_institucion_persona1`
    FOREIGN KEY (`persona_id_persona`)
    REFERENCES `persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recurso_obra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `recurso_obra` ;

CREATE TABLE IF NOT EXISTS `recurso_obra` (
  `id_recurso` INT NOT NULL,
  `descripcion_material` VARCHAR(45) NOT NULL,
  `cantidad_material` DECIMAL(5,2) NOT NULL,
  `unidad_material` VARCHAR(20) NOT NULL,
  `informe_avance_obra_id_informe` INT NOT NULL,
  PRIMARY KEY (`id_recurso`),
  INDEX `fk_recurso_obra_informe_avance_obra1_idx` (`informe_avance_obra_id_informe` ASC),
  CONSTRAINT `fk_recurso_obra_informe_avance_obra1`
    FOREIGN KEY (`informe_avance_obra_id_informe`)
    REFERENCES `informe_avance_obra` (`id_informe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_has_maquinaria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto_has_maquinaria` ;

CREATE TABLE IF NOT EXISTS `proyecto_has_maquinaria` (
  `proyecto_codigo_proyecto` VARCHAR(15) NOT NULL,
  `maquinaria_id_maquinaria` INT NOT NULL,
  PRIMARY KEY (`proyecto_codigo_proyecto`, `maquinaria_id_maquinaria`),
  INDEX `fk_proyecto_has_maquinaria_maquinaria1_idx` (`maquinaria_id_maquinaria` ASC),
  INDEX `fk_proyecto_has_maquinaria_proyecto1_idx` (`proyecto_codigo_proyecto` ASC),
  CONSTRAINT `fk_proyecto_has_maquinaria_proyecto1`
    FOREIGN KEY (`proyecto_codigo_proyecto`)
    REFERENCES `proyecto` (`codigo_proyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proyecto_has_maquinaria_maquinaria1`
    FOREIGN KEY (`maquinaria_id_maquinaria`)
    REFERENCES `maquinaria` (`id_maquinaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `gravedad_obra_has_prioridad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gravedad_obra_has_prioridad` ;

CREATE TABLE IF NOT EXISTS `gravedad_obra_has_prioridad` (
  `gravedad_obra_id_gravedad` INT NOT NULL,
  `prioridad_id_gestion_prioridad` INT NOT NULL,
  PRIMARY KEY (`gravedad_obra_id_gravedad`, `prioridad_id_gestion_prioridad`),
  INDEX `fk_gravedad_obra_has_prioridad_prioridad1_idx` (`prioridad_id_gestion_prioridad` ASC),
  INDEX `fk_gravedad_obra_has_prioridad_gravedad_obra1_idx` (`gravedad_obra_id_gravedad` ASC),
  CONSTRAINT `fk_gravedad_obra_has_prioridad_gravedad_obra1`
    FOREIGN KEY (`gravedad_obra_id_gravedad`)
    REFERENCES `gravedad_obra` (`id_gravedad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gravedad_obra_has_prioridad_prioridad1`
    FOREIGN KEY (`prioridad_id_gestion_prioridad`)
    REFERENCES `prioridad` (`id_gestion_prioridad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



