-- MySQL Script generated by MySQL Workbench
-- Sun Jun 14 20:53:49 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema invilara_seguridad
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema invilara_seguridad
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `invilara_seguridad` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci ;
USE `invilara_seguridad` ;

-- -----------------------------------------------------
-- Table `invilara_seguridad`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `invilara_seguridad`.`usuarios` (
  `id_usuarios` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) NOT NULL,
  `cedula_usuario` VARCHAR(10) NOT NULL,
  `contrasena` VARCHAR(255) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `rol` VARCHAR(20) NOT NULL COMMENT 'Tabla de los usuarios.',
  PRIMARY KEY (`id_usuarios`),
  UNIQUE INDEX `cedula_usuario_UNIQUE` (`cedula_usuario` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci
COMMENT = 'Tabla de usuarios';


-- -----------------------------------------------------
-- Table `invilara_seguridad`.`administracion_respaldos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `invilara_seguridad`.`administracion_respaldos` (
  `id_respaldo` INT NOT NULL AUTO_INCREMENT,
  `fecha_respaldo` DATETIME NOT NULL,
  `tamaño_respaldo` DECIMAL(4,2) NOT NULL,
  `usuarios_id_usuarios` INT NOT NULL,
  PRIMARY KEY (`id_respaldo`, `usuarios_id_usuarios`),
  INDEX `fk_administracion_respaldos_usuarios_idx` (`usuarios_id_usuarios` ASC),
  CONSTRAINT `fk_administracion_respaldos_usuarios`
    FOREIGN KEY (`usuarios_id_usuarios`)
    REFERENCES `invilara_seguridad`.`usuarios` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci
COMMENT = 'Tabla de administracion de respaldos.';


-- -----------------------------------------------------
-- Table `invilara_seguridad`.`bitacora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `invilara_seguridad`.`bitacora` (
  `id_bitacora` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(15) NOT NULL,
  `id_modulo` INT NOT NULL,
  `modulo` VARCHAR(20) NOT NULL,
  `accion` VARCHAR(45) NOT NULL,
  `fecha` DATETIME NOT NULL,
  `hora_inicio_sesion` DATETIME NOT NULL,
  `hora_cierre_sesion` DATETIME NOT NULL,
  `usuarios_id_usuarios` INT NOT NULL,
  PRIMARY KEY (`id_bitacora`, `usuarios_id_usuarios`),
  INDEX `fk_bitacora_usuarios1_idx` (`usuarios_id_usuarios` ASC),
  CONSTRAINT `fk_bitacora_usuarios1`
    FOREIGN KEY (`usuarios_id_usuarios`)
    REFERENCES `invilara_seguridad`.`usuarios` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci
COMMENT = 'Tabla de la bitacora del sistema.';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

