-- MySQL Script generated by MySQL Workbench
-- Sun Jun 14 20:23:22 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema invilara
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema invilara
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `invilara2` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `invilara` ;

-- -----------------------------------------------------
-- Table `invilara`.`empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invilara`.`empresa` ;

CREATE TABLE IF NOT EXISTS `invilara`.`empresa` (
  `rif` VARCHAR(12) NOT NULL,
  `nombre_empresa` VARCHAR(80) NOT NULL,
  `telefono` VARCHAR(12) NOT NULL COMMENT 'Tabla de empresas.',
  `domicilio_fiscal` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`rif`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `rif_UNIQUE` ON `invilara`.`empresa` (`rif` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `invilara`.`contratacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invilara`.`contratacion` ;

CREATE TABLE IF NOT EXISTS `invilara`.`contratacion` (
  `id_contratacion` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NOT NULL,
  `empresa_ganadora` VARCHAR(30) NOT NULL,
  `numero_contrato` VARCHAR(12) NOT NULL,
  `monto` VARCHAR(20) NOT NULL,
  `fecha_inicio_procedimiento` DATETIME NOT NULL,
  `fecha_adjudicacion` DATETIME NOT NULL,
  `tipo_contrato` VARCHAR(30) NOT NULL,
  `modalidad` VARCHAR(30) NOT NULL,
  `objeto` VARCHAR(30) NOT NULL,
  `observacion` VARCHAR(100) NOT NULL,
  `fecha_registro` DATETIME NOT NULL,
  `empresa_rif` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`id_contratacion`),
  CONSTRAINT `fk_contratacion_empresa1`
    FOREIGN KEY (`empresa_rif`)
    REFERENCES `invilara`.`empresa` (`rif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Tabla de contrataciones';

CREATE UNIQUE INDEX `numero_contrato_UNIQUE` ON `invilara`.`contratacion` (`numero_contrato` ASC) VISIBLE;

CREATE INDEX `fk_contratacion_empresa1_idx` ON `invilara`.`contratacion` (`empresa_rif` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `invilara`.`semaforo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invilara`.`semaforo` ;

CREATE TABLE IF NOT EXISTS `invilara`.`semaforo` (
  `id_semaforo` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(20) NOT NULL,
  `color` ENUM('VERDE', 'AMARILLO', 'ROJO') NOT NULL,
  `descripcion` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_semaforo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invilara`.`proyecto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invilara`.`proyecto` ;

CREATE TABLE IF NOT EXISTS `invilara`.`proyecto` (
  `codigo_proyecto` VARCHAR(15) NOT NULL,
  `fecha_planificacion` DATETIME NOT NULL,
  `descripcion_tecnica` VARCHAR(200) NOT NULL,
  `computos_metricos` VARCHAR(255) NOT NULL,
  `estimacion_costo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo_proyecto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla de gestion de proyectos';

CREATE UNIQUE INDEX `codigo_proyecto_UNIQUE` ON `invilara`.`proyecto` (`codigo_proyecto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `invilara`.`obra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invilara`.`obra` ;

CREATE TABLE IF NOT EXISTS `invilara`.`obra` (
  `id_obra` INT NOT NULL AUTO_INCREMENT,
  `titulo_obra` VARCHAR(45) NOT NULL,
  `ubicacion_obra` VARCHAR(80) NOT NULL,
  `periodo_ejecucion` INT NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `mediciones_obra` VARCHAR(45) NOT NULL,
  `valuaciones` VARCHAR(100) NOT NULL,
  `modificaciones_contrato` VARCHAR(100) NOT NULL,
  `certificaciones_obras_ejecutadas` INT NOT NULL,
  `numero_contrato` VARCHAR(20) NOT NULL,
  `porcentaje_avance_obra` INT NOT NULL,
  `semaforo_id_semaforo` INT NOT NULL,
  `contratacion_id_contratacion` INT NOT NULL,
  `gestionar_proyectos_codigo_proyecto` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_obra`, `semaforo_id_semaforo`, `contratacion_id_contratacion`, `gestionar_proyectos_codigo_proyecto`),
  CONSTRAINT `fk_obra_semaforo1`
    FOREIGN KEY (`semaforo_id_semaforo`)
    REFERENCES `invilara`.`semaforo` (`id_semaforo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_obra_contratacion1`
    FOREIGN KEY (`contratacion_id_contratacion`)
    REFERENCES `invilara`.`contratacion` (`id_contratacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_obra_gestionar_proyectos1`
    FOREIGN KEY (`gestionar_proyectos_codigo_proyecto`)
    REFERENCES `invilara`.`proyecto` (`codigo_proyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla de las inspecciones';

CREATE INDEX `fk_obra_semaforo1_idx` ON `invilara`.`obra` (`semaforo_id_semaforo` ASC) VISIBLE;

CREATE INDEX `fk_obra_contratacion1_idx` ON `invilara`.`obra` (`contratacion_id_contratacion` ASC) VISIBLE;

CREATE INDEX `fk_obra_gestionar_proyectos1_idx` ON `invilara`.`obra` (`gestionar_proyectos_codigo_proyecto` ASC) VISIBLE;

CREATE UNIQUE INDEX `id_obra_UNIQUE` ON `invilara`.`obra` (`id_obra` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `invilara`.`persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invilara`.`persona` ;

CREATE TABLE IF NOT EXISTS `invilara`.`persona` (
  `id_persona` INT NOT NULL AUTO_INCREMENT,
  `cedula_persona` INT NOT NULL,
  `direccion` VARCHAR(200) NOT NULL,
  `parroquia` VARCHAR(45) NOT NULL,
  `municipio` VARCHAR(45) NOT NULL,
  `telefono` TEXT(12) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_persona`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `cedula_persona_UNIQUE` ON `invilara`.`persona` (`cedula_persona` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `invilara`.`prioridad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invilara`.`prioridad` ;

CREATE TABLE IF NOT EXISTS `invilara`.`prioridad` (
  `id_gestion_prioridad` INT NOT NULL AUTO_INCREMENT,
  `rango_prioridad` FLOAT NOT NULL,
  `fecha_asignacion` DATETIME NOT NULL,
  `responsable_ajuste` VARCHAR(30) NOT NULL,
  `justificacion_cambio` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id_gestion_prioridad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invilara`.`solicitudes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invilara`.`solicitudes` ;

CREATE TABLE IF NOT EXISTS `invilara`.`solicitudes` (
  `id_solicitudes` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `tipo_solicitud` VARCHAR(45) NOT NULL,
  `estatus_solicitud` VARCHAR(15) NOT NULL,
  `problematica` VARCHAR(255) NOT NULL,
  `persona_id_persona` INT NOT NULL,
  `prioridad_id_gestion_prioridad` INT NOT NULL,
  PRIMARY KEY (`id_solicitudes`, `persona_id_persona`, `prioridad_id_gestion_prioridad`),
  CONSTRAINT `fk_solicitudes_persona1`
    FOREIGN KEY (`persona_id_persona`)
    REFERENCES `invilara`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitudes_prioridad1`
    FOREIGN KEY (`prioridad_id_gestion_prioridad`)
    REFERENCES `invilara`.`prioridad` (`id_gestion_prioridad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla general de las solicitudes';

CREATE INDEX `fk_solicitudes_persona1_idx` ON `invilara`.`solicitudes` (`persona_id_persona` ASC) VISIBLE;

CREATE INDEX `fk_solicitudes_prioridad1_idx` ON `invilara`.`solicitudes` (`prioridad_id_gestion_prioridad` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `invilara`.`avance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invilara`.`avance` ;

CREATE TABLE IF NOT EXISTS `invilara`.`avance` (
  `id_avance` VARCHAR(45) NOT NULL,
  `porcentaje_avance` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `gerente` VARCHAR(45) NOT NULL,
  `fecha_avance` DATE NOT NULL,
  `obra_id_obra` INT NOT NULL,
  `obra_semaforo_id_semaforo` INT NOT NULL,
  `obra_contratacion_id_contratacion` INT NOT NULL,
  `obra_gestionar_proyectos_codigo_proyecto` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_avance`),
  CONSTRAINT `fk_avance_obra1`
    FOREIGN KEY (`obra_id_obra` , `obra_semaforo_id_semaforo` , `obra_contratacion_id_contratacion` , `obra_gestionar_proyectos_codigo_proyecto`)
    REFERENCES `invilara`.`obra` (`id_obra` , `semaforo_id_semaforo` , `contratacion_id_contratacion` , `gestionar_proyectos_codigo_proyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_avance_obra1_idx` ON `invilara`.`avance` (`obra_id_obra` ASC, `obra_semaforo_id_semaforo` ASC, `obra_contratacion_id_contratacion` ASC, `obra_gestionar_proyectos_codigo_proyecto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `invilara`.`informe_avance_obra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invilara`.`informe_avance_obra` ;

CREATE TABLE IF NOT EXISTS `invilara`.`informe_avance_obra` (
  `id_informe` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `estado` VARCHAR(25) NOT NULL,
  `poblacion_benefiada` VARCHAR(45) NOT NULL,
  `tipo_informe` VARCHAR(30) NOT NULL,
  `evidencia_antes` VARCHAR(50) NOT NULL,
  `evidencia_durante` VARCHAR(50) NOT NULL,
  `evidencia_despues` VARCHAR(50) NOT NULL,
  `avance_id_avance` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_informe`),
  CONSTRAINT `fk_informe_avance_obra_avance1`
    FOREIGN KEY (`avance_id_avance`)
    REFERENCES `invilara`.`avance` (`id_avance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla de informes de avances de obras';

CREATE INDEX `fk_informe_avance_obra_avance1_idx` ON `invilara`.`informe_avance_obra` (`avance_id_avance` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `invilara`.`reporte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invilara`.`reporte` ;

CREATE TABLE IF NOT EXISTS `invilara`.`reporte` (
  `id_reporte` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `ubicacion` VARCHAR(255) NOT NULL,
  `solicitudes_pendientes` INT NOT NULL,
  `solicitudes_procesadas` INT NOT NULL,
  `cantidad_total_solicitudes` INT NOT NULL,
  `cantidad_comunidades_atendidas` INT NOT NULL,
  `informe_avance_obra_id_informe` INT NOT NULL,
  PRIMARY KEY (`id_reporte`),
  CONSTRAINT `fk_reporte_informe_avance_obra1`
    FOREIGN KEY (`informe_avance_obra_id_informe`)
    REFERENCES `invilara`.`informe_avance_obra` (`id_informe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `fk_reporte_informe_avance_obra1_idx` ON `invilara`.`reporte` (`informe_avance_obra_id_informe` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `invilara`.`maquinaria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invilara`.`maquinaria` ;

CREATE TABLE IF NOT EXISTS `invilara`.`maquinaria` (
  `id_maquinaria` INT NOT NULL AUTO_INCREMENT,
  `nombre_maquinaria` VARCHAR(50) NOT NULL COMMENT 'Tabla de nombres de maquinarias',
  `tipo_maquinaria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_maquinaria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invilara`.`evidencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invilara`.`evidencia` ;

CREATE TABLE IF NOT EXISTS `invilara`.`evidencia` (
  `id_evidencia` INT NOT NULL AUTO_INCREMENT,
  `fotos` VARCHAR(45) NOT NULL,
  `url_archivos` VARCHAR(90) NOT NULL,
  `fecha_registro` DATETIME NOT NULL,
  PRIMARY KEY (`id_evidencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invilara`.`inspeccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invilara`.`inspeccion` ;

CREATE TABLE IF NOT EXISTS `invilara`.`inspeccion` (
  `id_inspeccion` INT NOT NULL AUTO_INCREMENT,
  `inspector` VARCHAR(45) NOT NULL,
  `fecha_inspeccion` DATE NOT NULL,
  `tipo_inspeccion` VARCHAR(45) NOT NULL,
  `observaciones` VARCHAR(255) NOT NULL,
  `obra_id_obra` INT NOT NULL,
  `obra_semaforo_id_semaforo` INT NOT NULL,
  `obra_contratacion_id_contratacion` INT NOT NULL,
  `obra_gestionar_proyectos_codigo_proyecto` VARCHAR(15) NOT NULL,
  `obra_id_obra1` INT NOT NULL,
  `obra_semaforo_id_semaforo1` INT NOT NULL,
  `obra_contratacion_id_contratacion1` INT NOT NULL,
  `obra_gestionar_proyectos_codigo_proyecto1` VARCHAR(15) NOT NULL,
  `evidencia_id_evidencia` INT NOT NULL,
  PRIMARY KEY (`id_inspeccion`, `evidencia_id_evidencia`),
  CONSTRAINT `fk_inspeccion_obra1`
    FOREIGN KEY (`obra_id_obra1` , `obra_semaforo_id_semaforo1` , `obra_contratacion_id_contratacion1` , `obra_gestionar_proyectos_codigo_proyecto1`)
    REFERENCES `invilara`.`obra` (`id_obra` , `semaforo_id_semaforo` , `contratacion_id_contratacion` , `gestionar_proyectos_codigo_proyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inspeccion_evidencia1`
    FOREIGN KEY (`evidencia_id_evidencia`)
    REFERENCES `invilara`.`evidencia` (`id_evidencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `cedula_UNIQUE` ON `invilara`.`inspeccion` (`fecha_inspeccion` ASC) VISIBLE;

CREATE INDEX `fk_inspeccion_obra1_idx` ON `invilara`.`inspeccion` (`obra_id_obra1` ASC, `obra_semaforo_id_semaforo1` ASC, `obra_contratacion_id_contratacion1` ASC, `obra_gestionar_proyectos_codigo_proyecto1` ASC) VISIBLE;

CREATE INDEX `fk_inspeccion_evidencia1_idx` ON `invilara`.`inspeccion` (`evidencia_id_evidencia` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `invilara`.`empleados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invilara`.`empleados` ;

CREATE TABLE IF NOT EXISTS `invilara`.`empleados` (
  `id_empleados` INT NOT NULL AUTO_INCREMENT,
  `nombre_empleado` VARCHAR(45) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `fecha_ingreso` DATE NOT NULL,
  `gerencia_asignada` VARCHAR(45) NOT NULL,
  `persona_id_persona` INT NOT NULL,
  PRIMARY KEY (`id_empleados`),
  CONSTRAINT `fk_empleados_persona1`
    FOREIGN KEY (`persona_id_persona`)
    REFERENCES `invilara`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_empleados_persona1_idx` ON `invilara`.`empleados` (`persona_id_persona` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `invilara`.`gravedad_obra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invilara`.`gravedad_obra` ;

CREATE TABLE IF NOT EXISTS `invilara`.`gravedad_obra` (
  `id_gravedad` INT NOT NULL AUTO_INCREMENT,
  `nivel_gravedad` VARCHAR(20) NOT NULL,
  `criticidad` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_gravedad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invilara`.`publicacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invilara`.`publicacion` ;

CREATE TABLE IF NOT EXISTS `invilara`.`publicacion` (
  `id_publicacion` INT NOT NULL AUTO_INCREMENT,
  `titulo_publicacion` VARCHAR(150) NOT NULL,
  `nombre_responsable` VARCHAR(45) NOT NULL,
  `tipo_publicacion` VARCHAR(15) NOT NULL,
  `fecha_publicacion` DATETIME NOT NULL COMMENT 'Tabla de gestion de publicaciones',
  `informe_avance_obra_id_informe` INT NOT NULL,
  PRIMARY KEY (`id_publicacion`),
  CONSTRAINT `fk_publicacion_informe_avance_obra1`
    FOREIGN KEY (`informe_avance_obra_id_informe`)
    REFERENCES `invilara`.`informe_avance_obra` (`id_informe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_publicacion_informe_avance_obra1_idx` ON `invilara`.`publicacion` (`informe_avance_obra_id_informe` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `invilara`.`particular`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invilara`.`particular` ;

CREATE TABLE IF NOT EXISTS `invilara`.`particular` (
  `id_particular` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `persona_id_persona` INT NOT NULL,
  PRIMARY KEY (`id_particular`, `persona_id_persona`),
  CONSTRAINT `fk_particular_persona1`
    FOREIGN KEY (`persona_id_persona`)
    REFERENCES `invilara`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_particular_persona1_idx` ON `invilara`.`particular` (`persona_id_persona` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `invilara`.`comunidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invilara`.`comunidad` ;

CREATE TABLE IF NOT EXISTS `invilara`.`comunidad` (
  `id_comunidad` INT NOT NULL AUTO_INCREMENT,
  `nombre_comunidad` VARCHAR(100) NOT NULL,
  `ambito` VARCHAR(45) NOT NULL,
  `sector` VARCHAR(45) NOT NULL,
  `persona_id_persona` INT NOT NULL,
  PRIMARY KEY (`id_comunidad`, `persona_id_persona`),
  CONSTRAINT `fk_comunidad_persona1`
    FOREIGN KEY (`persona_id_persona`)
    REFERENCES `invilara`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_comunidad_persona1_idx` ON `invilara`.`comunidad` (`persona_id_persona` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `invilara`.`institucion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invilara`.`institucion` ;

CREATE TABLE IF NOT EXISTS `invilara`.`institucion` (
  `id_institucion` INT NOT NULL AUTO_INCREMENT,
  `nombre_representante` VARCHAR(45) NOT NULL,
  `razon_social` VARCHAR(120) NOT NULL,
  `persona_id_persona` INT NOT NULL,
  PRIMARY KEY (`id_institucion`, `persona_id_persona`),
  CONSTRAINT `fk_institucion_persona1`
    FOREIGN KEY (`persona_id_persona`)
    REFERENCES `invilara`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_institucion_persona1_idx` ON `invilara`.`institucion` (`persona_id_persona` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `invilara`.`recurso_obra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invilara`.`recurso_obra` ;

CREATE TABLE IF NOT EXISTS `invilara`.`recurso_obra` (
  `id_recurso` INT NOT NULL,
  `descripcion_material` VARCHAR(45) NOT NULL,
  `cantidad_material` DECIMAL(5,2) NOT NULL,
  `unidad_material` VARCHAR(20) NOT NULL,
  `informe_avance_obra_id_informe` INT NOT NULL,
  PRIMARY KEY (`id_recurso`),
  CONSTRAINT `fk_recurso_obra_informe_avance_obra1`
    FOREIGN KEY (`informe_avance_obra_id_informe`)
    REFERENCES `invilara`.`informe_avance_obra` (`id_informe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_recurso_obra_informe_avance_obra1_idx` ON `invilara`.`recurso_obra` (`informe_avance_obra_id_informe` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `invilara`.`proyecto_has_maquinaria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invilara`.`proyecto_has_maquinaria` ;

CREATE TABLE IF NOT EXISTS `invilara`.`proyecto_has_maquinaria` (
  `proyecto_codigo_proyecto` VARCHAR(15) NOT NULL,
  `maquinaria_id_maquinaria` INT NOT NULL,
  PRIMARY KEY (`proyecto_codigo_proyecto`, `maquinaria_id_maquinaria`),
  CONSTRAINT `fk_proyecto_has_maquinaria_proyecto1`
    FOREIGN KEY (`proyecto_codigo_proyecto`)
    REFERENCES `invilara`.`proyecto` (`codigo_proyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proyecto_has_maquinaria_maquinaria1`
    FOREIGN KEY (`maquinaria_id_maquinaria`)
    REFERENCES `invilara`.`maquinaria` (`id_maquinaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_proyecto_has_maquinaria_maquinaria1_idx` ON `invilara`.`proyecto_has_maquinaria` (`maquinaria_id_maquinaria` ASC) VISIBLE;

CREATE INDEX `fk_proyecto_has_maquinaria_proyecto1_idx` ON `invilara`.`proyecto_has_maquinaria` (`proyecto_codigo_proyecto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `invilara`.`gravedad_obra_has_prioridad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invilara`.`gravedad_obra_has_prioridad` ;

CREATE TABLE IF NOT EXISTS `invilara`.`gravedad_obra_has_prioridad` (
  `gravedad_obra_id_gravedad` INT NOT NULL,
  `prioridad_id_gestion_prioridad` INT NOT NULL,
  PRIMARY KEY (`gravedad_obra_id_gravedad`, `prioridad_id_gestion_prioridad`),
  CONSTRAINT `fk_gravedad_obra_has_prioridad_gravedad_obra1`
    FOREIGN KEY (`gravedad_obra_id_gravedad`)
    REFERENCES `invilara`.`gravedad_obra` (`id_gravedad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gravedad_obra_has_prioridad_prioridad1`
    FOREIGN KEY (`prioridad_id_gestion_prioridad`)
    REFERENCES `invilara`.`prioridad` (`id_gestion_prioridad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_gravedad_obra_has_prioridad_prioridad1_idx` ON `invilara`.`gravedad_obra_has_prioridad` (`prioridad_id_gestion_prioridad` ASC) VISIBLE;

CREATE INDEX `fk_gravedad_obra_has_prioridad_gravedad_obra1_idx` ON `invilara`.`gravedad_obra_has_prioridad` (`gravedad_obra_id_gravedad` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
